package org.slixes.platform.openai.completion.chat;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.extern.jackson.Jacksonized;

/**
 * A chat completion generated by OpenAI
 */
@Data
@Builder
@Jacksonized
public class ChatCompletionChoice {

  /**
   * This index of this completion in the returned list.
   */
  Integer index;

  @JsonAlias("delta")
  ChatMessage message;

  /**
   * The reason why GPT stopped generating, for example "length".
   */
  @JsonProperty("finish_reason")
  String finishReason;
}
