name: Build
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Maven 3.9.4
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.9.4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'

      - name: Run Tests
        run: mvn test
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

      - name: Build with Maven
        run: mvn package -DskipTests

